from datetime import datetime, timezone
from typing import Any, Dict
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.utils.logger import get_logger
from app.schemas.charter_version import CharterVersion  # adjust import path to your SQLAlchemy model
from app.models.pydantic_models import ProjectCharter

logger = get_logger(__name__)


async def create_charter_version(
    session: AsyncSession,
    *,
    charter: ProjectCharter,
    user_id: UUID,
) -> CharterVersion:
    """
    Insert a new row into charter_versions as an immutable snapshot
    of the given charter.

    For now this is called on initial charter creation. In future,
    call this again whenever a charter is edited.
    """

    if not charter.charter_id:
        raise ValueError("charter.charter_id is required to create a charter version")

    now = datetime.now(timezone.utc)

    # Full JSON snapshot (Pydantic -> plain dict)
    charter_json: Dict[str, Any] = charter.model_dump()

    version_row = CharterVersion(
        # version_id is assumed to be auto-generated by the DB (IDENTITY / SERIAL)
        charter_id=charter.charter_id,
        version_by=user_id,
        version_at=now,
        charter_json=charter_json,
    )

    session.add(version_row)
    await session.flush()  # get generated version_id if needed

    logger.info(
        "Created charter_versions row %s for charter %s",
        getattr(version_row, "version_id", None),
        charter.charter_id,
    )

    return version_row
